/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDienSach;

import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FrameForm extends javax.swing.JFrame {

    /**
     * Creates new form FrameForm
     */
    public FrameForm() {
        initComponents();
        loadCompobox();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb_Tentacgia = new javax.swing.JComboBox<>();
        jTextField_Tensach = new javax.swing.JTextField();
        jTextField_Looaisach = new javax.swing.JTextField();
        jTextField_Hinhanh = new javax.swing.JTextField();
        jTextField_Sotrang = new javax.swing.JTextField();
        jTextField_Mota = new javax.swing.JTextField();
        jTextField_Giasach = new javax.swing.JTextField();
        jTextField_Soluong = new javax.swing.JTextField();
        jTextField_NXB = new javax.swing.JTextField();
        jTextField_kichthuoc = new javax.swing.JTextField();
        jTextField_SKU = new javax.swing.JTextField();
        jButton_Them = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Hienthi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên sách:");

        jLabel2.setText("Tên tác gả:");

        jLabel3.setText("Loại sách:");

        jLabel4.setText("Hình ảnh:");

        jLabel5.setText("Giá sách:");

        jLabel6.setText("Số lượng:");

        jLabel7.setText("Ngày xuất bản");

        jLabel8.setText("Kích thước");

        jLabel9.setText("Số trang");

        jLabel10.setText("SKU");

        jLabel11.setText("Mô Tả:");

        cb_Tentacgia.setEditable(true);
        cb_Tentacgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TentacgiaActionPerformed(evt);
            }
        });

        jTextField_Mota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MotaActionPerformed(evt);
            }
        });

        jTextField_SKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SKUActionPerformed(evt);
            }
        });

        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Hienthi.setText("Hiển thị thông tin");
        jButton_Hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HienthiActionPerformed(evt);
            }
        });

        jButton1.setText("TEST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_Looaisach, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(jTextField_Hinhanh)
                                .addComponent(jTextField_Sotrang)
                                .addComponent(jTextField_Mota))
                            .addComponent(jTextField_Tensach, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_Tentacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Giasach)
                            .addComponent(jTextField_Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_SKU)
                                    .addComponent(jTextField_kichthuoc)
                                    .addComponent(jTextField_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton_Hienthi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField_Tensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(cb_Tentacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Looaisach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_Giasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_kichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_Sotrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_Mota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_Hienthi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jTextField_MotaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void luuSach(String tensach, String loaisach, String hinh, int soluong, String ngayXB, String kichthuoc, String sotrang, String gia, String sku, String mota, String tentg) {
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String sql = "INSERT into SACH values(?,?,?,?,?,?,?,?,?,?,?)";
        try {

            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, tensach);
            ps.setString(2, loaisach);
            ps.setString(3, hinh);
            ps.setInt(4, soluong);
            ps.setString(5, ngayXB);
            ps.setString(6, kichthuoc);
            ps.setString(7, sotrang);
            ps.setString(8, sku);
            ps.setString(9, gia);
            ps.setString(10, mota);
            ps.setString(11, tentg);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadCompobox() {
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String sql = "select * from TACGIA";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cb_Tentacgia.addItem(rs.getString("TENTG"));

            }
            System.out.println("LOAD COMBOBOX THÀNH CÔNG!");

        } catch (SQLException ex) {
            Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private int kiemTraSach(String tenSach) {
        java.sql.Connection ketNoi = KetNoiMSSQL.layKetNoi();
        int tonTai = 0;
        String sql = "select * from SACH where TENSACH = N'" + tenSach + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tonTai = 1;
            }
            rs.close();
            ps.close();
            ketNoi.close();
        } catch (SQLException e) {
            Logger.getLogger(TH.class.getName()).log(Level.SEVERE, null, e);
        }
        return tonTai;
    }

    private void xoaSach(String tenSach) {
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String sql = "DELETE from SACH where TENSACH = ?";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, tenSach);
            ps.executeUpdate();
        } catch (SQLException e) {
            Logger.getLogger(TH.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void hienThi(String tenSach) {
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String sql = "select * from SACH where TENSACH = N'" + tenSach + "'";
        String tensach, hinh, ngayXB, kichthuoc, sotrang, gia, sku, mota, tentg;

        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                tensach = rs.getString("TENSACH");
                hinh = rs.getString("HINH");
                ngayXB = rs.getString("NGAYXB");
                kichthuoc = rs.getString("KICHTHUOC");
                sotrang = String.valueOf(rs.getInt("SOTRANG"));
                gia = rs.getString("GIA");
                sku = rs.getString("SKU");
                mota = rs.getString("MOTA");
                tentg = rs.getString("TENTG");
                TH th;
                try {
                    th = new TH();
                    th.setThongTin(tensach, hinh, ngayXB, kichthuoc, sotrang, gia, sku, mota, tentg);
                    th.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            rs.close();
            ps.close();
            ketNoi.close();

        } catch (SQLException ex) {
            Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void jTextField_SKUActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        String tensach = jTextField_Tensach.getText();
        String loaisach = jTextField_Looaisach.getText();
        String hinh = jTextField_Hinhanh.getText();
        String ngayXB = jTextField_NXB.getText();
        int soluong = Integer.parseInt(jTextField_Soluong.getText());
        String kichthuoc = jTextField_kichthuoc.getText();
        String gia = jTextField_Giasach.getText();
        String sotrang = jTextField_Sotrang.getText();
        String sku = jTextField_Giasach.getText();
        String mota = jTextField_Mota.getText();
        String tentg = String.valueOf(cb_Tentacgia.getSelectedItem());
        luuSach(tensach, loaisach, hinh, soluong, ngayXB, kichthuoc, sotrang, sku, gia, mota, tentg);
    }                                            

    private void cb_TentacgiaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String tenSach = jTextField_Tensach.getText();
        int check;
        int kiemTraSach = 0;
        if (tenSach.equals("")) {
            kiemTraSach = 1;
            JOptionPane.showConfirmDialog(this, "Hay nhap ten sach ban muon xoa");
        } else if (kiemTraSach != 1) {
            check = kiemTraSach(tenSach);
            if (check == 1) {
                int ret = JOptionPane.showConfirmDialog(this, "Ban co chac ban muon xoa?", "Xac nhan", 0);
                if (ret == JOptionPane.CANCEL_OPTION) {
                    return;
                } else {
                    if (ret == JOptionPane.OK_OPTION) {
                        xoaSach(tenSach);
                        JOptionPane.showConfirmDialog(this, "Xoa sach thanh cong");
                    }

                }
            } else {
                JOptionPane.showConfirmDialog(this, "Sach nay chua co, hay them thong tin sach vao he thong");
            }

        }

    }                                           

     private void chinhSua(String tensach, String loaisach, String hinh, int soluong, String ngayXB, String kichthuoc, String sotrang, String gia, String sku, String mota, String tentg) {
        Connection ketNoi = KetNoiMSSQL.layKetNoi();
        String sql = "update SACH set ";
        if (!tensach.equals("")) {
            sql += "TENSACH=N'" + tensach + "'";
        }
        if (!loaisach.equals("")) {
            sql += ",LOAISACH = N'" + loaisach + "'";
        }
        if (!hinh.equals("")) {
            sql += ",HINH = N'" + hinh + "'";
        }
        if (!String.valueOf(soluong).equals("")) {
            sql += ",SOLUONG = " + soluong;
        }
        if (!ngayXB.equals("")) {
            sql += ",NGAYXB = N'" + ngayXB + "'";
        }
        if (!sotrang.equals("")) {
            sql += ",SOTRANG =N'" + sotrang + "'";
        }
        if (!sku.equals("")) {
            sql += ",SKU = N'" + sku + "'";
        }
        if (!gia.equals("")) {
            sql += ",GIA= N'" + gia + "'";
        }
        if (!mota.equals("")) {
            sql += ",MOTA = N'" + mota + "'";
        }
        if (!tentg.equals("")) {
            sql += ",TENTG = N'" + tentg + "'";
        }
        sql += "where TENSACH = N'"+tensach+"'";
        System.out.println(sql);
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.executeUpdate();
            System.out.println("Chinh sua thanh cong!");

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, "Sach chưa có trong hệ thống");
            Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
     
    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String tensach = jTextField_Tensach.getText();
        String loaisach = jTextField_Looaisach.getText();
        String hinh = jTextField_Hinhanh.getText();
        String ngayXB = jTextField_NXB.getText();
        int soluong = Integer.parseInt(jTextField_Soluong.getText());
        String kichthuoc = jTextField_kichthuoc.getText();
        String gia = jTextField_Giasach.getText();
        String sotrang = jTextField_Sotrang.getText();
        String sku = jTextField_Giasach.getText();
        String mota = jTextField_Mota.getText();
        String tentg = String.valueOf(cb_Tentacgia.getSelectedItem());
        System.out.println(kiemTraSach(tensach));
        if (kiemTraSach(tensach) == 1)
            chinhSua(tensach, loaisach, hinh, soluong, ngayXB, kichthuoc, sotrang, gia, sku, mota, tentg);
    }                                           

    private void jButton_HienthiActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String tenSach = jTextField_Tensach.getText();
        
        if (kiemTraSach(tenSach) == 1){ 
            hienThi(tenSach);
    }
        else
            JOptionPane.showConfirmDialog(this, "Sach khong ton tai!");

    }                                               
    
    private void kiemTraTG(){
        String tg = cb_Tentacgia.getSelectedItem().toString();
        boolean kt = true;
        for (int i=0;i<cb_Tentacgia.getItemCount();i++)
            if (tg.equals(cb_Tentacgia.getItemAt(i)))
                  kt = true;
             else{
                kt = false;
                break;
            }
        if (kt==false)
        {
            Connection ketNoi = KetNoiMSSQL.layKetNoi();
            String sql = "insert into TACGIA values(?)";
            try {
                
                PreparedStatement ps = ketNoi.prepareStatement(sql);
                ps.setString(1, tg);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String s = cb_Tentacgia.getSelectedItem().toString();
        kiemTraTG();
    }                                        

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cb_Tentacgia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Hienthi;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_Giasach;
    private javax.swing.JTextField jTextField_Hinhanh;
    private javax.swing.JTextField jTextField_Looaisach;
    private javax.swing.JTextField jTextField_Mota;
    private javax.swing.JTextField jTextField_NXB;
    private javax.swing.JTextField jTextField_SKU;
    private javax.swing.JTextField jTextField_Soluong;
    private javax.swing.JTextField jTextField_Sotrang;
    private javax.swing.JTextField jTextField_Tensach;
    private javax.swing.JTextField jTextField_kichthuoc;
    // End of variables declaration                   
}
